<a href="https://colab.research.google.com/github/junho2000/numpy-practice/blob/main/numpy_%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##모듈과 패키지

#모듈은 변수 함수 클래스를 담고 있는 파일 (.pt)
#패키지는 여러 모듈을 묶은 것(폴더)
#import 모듈
#모듈.변수
#모듈.함수()
#모듈.클래스

In [ ]:
import math
print(math.pi)
print(math.sqrt(4))

3.141592653589793
2.0


In [ ]:
import math as m
print(m.pi)
print(m.sqrt(4))

3.141592653589793
2.0


In [ ]:
from math import pi,sqrt
print(pi)
print(sqrt(4))

3.141592653589793
2.0


In [ ]:
from math import * #all
print(pi)
print(sqrt(4))
print(sin(pi))

3.141592653589793
2.0
1.2246467991473532e-16


In [ ]:
from math import sqrt as s
print(s(4))

2.0


In [ ]:
from math import sqrt as s, pi as p
print(p)
print(s(4))

3.141592653589793
2.0


In [ ]:
import numpy as np #numerical python
a=np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
import numpy.random
print(numpy.random.randn(3,3)) #Standard Normal dist (3,3) 3행 3열 sample 추출 iid
print(numpy.random.rand(3,3)) #uniform dist 0~1

[[-0.02379488 -0.21788401  0.28473919]
 [ 1.1052346  -0.87251687 -0.75991053]
 [-1.36910406 -0.9456586  -1.40555683]]
[[0.31123696 0.92597216 0.38666807]
 [0.50669669 0.45255791 0.68466845]
 [0.48576306 0.4326721  0.47253862]]


In [ ]:
import numpy.random as nr
print(nr.randn(3,3))

[[ 0.42600942  0.4388549  -0.42107856]
 [-0.76272375  0.29374132 -1.3998826 ]
 [ 0.18414941 -0.66462801  1.16669909]]


In [ ]:
from numpy.random import randn
print(randn(3,3))

[[ 0.4729115   0.25429559  1.27414988]
 [-0.91277229  1.08727111 -1.85744792]
 [ 1.77840846 -0.55028147  1.16382994]]


In [ ]:
from numpy.random import *
print(rand(3,3))

[[0.76300226 0.05957398 0.67923849]
 [0.91508254 0.52997619 0.80099602]
 [0.26639312 0.05289091 0.61495339]]


In [ ]:
from numpy.random import randn as rn
print(rn(3,3))

[[-0.99217194  1.70004557  0.24619391]
 [-0.78017667  0.87964596  0.03812821]
 [ 0.73573686 -0.47904118  1.95304722]]


#numpy

In [ ]:
from numpy.random import randn as rn, rand as r
print(rn(3,3))
print(r(3,3))

[[ 0.40839887 -0.61302064 -0.15877633]
 [-1.40532193 -0.1041714  -0.64932219]
 [ 1.89093814  0.18739763 -1.28207663]]
[[0.9411354  0.77159213 0.0306434 ]
 [0.55091514 0.46719417 0.1037041 ]
 [0.33214887 0.4539872  0.50953979]]


In [ ]:
import numpy as np
a=np.array([1,2,3]) #list를 입력으로 들어가는 함수
print(a)
print(type(a)) 
print(a.dtype) #data type
print(a.shape)
print(a[0])

b=np.array([1,2,3.1,4]) #하나만 float이면 자동으로 다 float
print(type(b[1]))
print(b.dtype)
print(b[0])

[1 2 3]
<class 'numpy.ndarray'>
int64
(3,)
1
<class 'numpy.float64'>
float64
1.0


In [ ]:
a=np.array(2**63-1) #overflow 안남
print(a)
print(a.dtype)

9223372036854775807
int64


In [ ]:
A=np.array([[1,2],[3,4]])
# A=np.array([[1,2],[3,4,5]]) #리스트와는 달리 이제는 행렬이라서 각각 행에 해당하는 숫자의 개수가 같아야함
print(A)
print(A.shape)
print(A.ndim) #차원의 수, 대괄호가 몇개인지
print(A.size)

[[1 2]
 [3 4]]
(2, 2)
2
4


In [ ]:
print(np.zeros(5))
print(np.zeros_like(A)) #A의 사이즈에 맞게 0을 채워줌
print(np.ones(5))
print(np.ones_like(A))
print(np.zeros((3,3))) #list or tuple로 하나로 묶어줘야함
print(np.arange(3,10,2)) #range와 같은데 array로 만들어줌
print(np.arange(0,1,0.1))# 소수점 가능 0<= <1
print(np.linspace(0,1,10))#0부터 1포함(default) 10개로
print(np.linspace(0,1,10,endpoint=False))#from 0 to 1(except)


[0. 0. 0. 0. 0.]
[[0 0]
 [0 0]]
[1. 1. 1. 1. 1.]
[[1 1]
 [1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[3 5 7 9]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
c=a+b
print(c)# 양옆으로 길어지는게 아닌 벡터의 합이 나옴
[1,2,3]+[4,5,6]

[5 7 9]


[1, 2, 3, 4, 5, 6]

In [ ]:
A=np.array([[1,2,3],[1,2,3]])
B=np.array([[4,5,6],[1,1,1]])
C=A+B
D=A-B
print(C)
print(D)
print(A*B) #성분끼리의의 곱 (Hadamard product)
print(A/B) #나누기도 성분끼리
print(B**2)#제곱도도 각각 성분에 대해 해준다
[[1,2,3],[1,2,3]]+[[4,5,6],[1,1,1]]

[[5 7 9]
 [2 3 4]]
[[-3 -3 -3]
 [ 0  1  2]]
[[ 4 10 18]
 [ 1  2  3]]
[[0.25 0.4  0.5 ]
 [1.   2.   3.  ]]
[[16 25 36]
 [ 1  1  1]]


[[1, 2, 3], [1, 2, 3], [4, 5, 6], [1, 1, 1]]

In [ ]:
A=np.array([[1,2],[3,4]])
B=np.array([[1,2],[3,4]])
print(A*B)
print(A@B) #matric muplication

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


#numpy의 인덱싱과 슬라이딩

In [ ]:
#list indexing
a=np.array([1,2,3,4,5,6,7,8,9])
print(a[0])
print(a[1])
print(a[-1])
print(a[1:4])
print(a[7:])
print(a[:])


1
2
9
[2 3 4]
[8 9]
[1 2 3 4 5 6 7 8 9]


In [ ]:
#matrix indexing
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A[0])
print(A[-1])
print(A[1:])
print(A[:])
print(A[0][2])
print(A[0,2]) #only possible in numpy
print(A[1,:])
print(A[1,0:3:2])
print(A[:,2])

[1 2 3]
[7 8 9]
[[4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
3
3
[4 5 6]
[4 6]
[3 6 9]


In [ ]:
#boolean indexing, true false
a=[1,2,3,4,5,3,3]
print(a==3) #여러개 값이 들어가 있는 리스트랑 3달랑 하나랑 같나?
A=np.array([[1,2,3,4],[5,3,7,3]])
print(A==3)#리스트와 달리 각 요소에 대해 비교
print(A[A==3]) #true인 지점에 해당하는 성분만을 인덱싱한다 A[index]

A[A==3]=100 #3과 같은 애를 100으로 바꿈
print(A)

A=np.array([[1,2],[3,4],[5,6],[7,8]])
B=np.array([True,False,False,True])
A[B,:]

b=np.array([1,2,3,4])
print(b)
print(b[[True,False,True,False]])

#c=[1,2,3,4]
#c[[True,False,True,False]]

False
[[False False  True False]
 [False  True False  True]]
[3 3 3]
[[  1   2 100   4]
 [  5 100   7 100]]
[1 2 3 4]
[1 3]


In [ ]:
#3차원 행렬의 인덱싱
A=np.array([[[0,1,2,3],[4,5,6,7],[8,9,10,11]],
           [[12,13,14,15],[16,17,18,19],[20,21,22,23]]])
print(A)
print(A.shape) #3x4 matrix가 2개, 대괄호가 하나가 늘어나면 왼쪽 shape값이 추가된다
print(A[0,1,2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
6


#numpy의 여러함수들

In [ ]:
A=np.random.randn(3,3) #튜플로 안줘도 됨
B=np.random.rand(3,3)
print(A)
print(B)
print(A[A[:,0]<0,:])

[[-0.24011494  0.91253376 -0.95892242]
 [-1.08123114  0.90006315 -0.4791053 ]
 [ 1.65340607  1.73015319 -0.88796456]]
[[0.25522417 0.38026951 0.30719665]
 [0.58139498 0.64723158 0.82905062]
 [0.1163506  0.06346306 0.14615585]]
[[-0.24011494  0.91253376 -0.95892242]
 [-1.08123114  0.90006315 -0.4791053 ]]


In [ ]:
A=np.random.randn(3,3)
print(A)
print(np.abs(A))
print(np.sqrt(np.abs(A)))
print(np.exp(A))
print(np.log(np.abs(A)))
print(np.log(np.exp(1))) #log밑이 자연상수 => e
print(np.log10(10))
print(np.log2(2))
print(np.round(A,2)) #소수점 둘째 자리까지 반올림
print(np.floor(A)) #내림
print(np.ceil(A)) #올림

[[ 0.31571175  1.20411154 -1.56095857]
 [-0.28740197  1.24965342  0.585505  ]
 [-0.25312571  0.87278698 -0.82175748]]
[[0.31571175 1.20411154 1.56095857]
 [0.28740197 1.24965342 0.585505  ]
 [0.25312571 0.87278698 0.82175748]]
[[0.56188233 1.09732016 1.24938328]
 [0.53609884 1.11787898 0.76518298]
 [0.503116   0.93423069 0.9065084 ]]
[[1.37123494 3.33379583 0.20993474]
 [0.75021011 3.48913347 1.79589768]
 [0.77637028 2.3935724  0.43965828]]
[[-1.15292567  0.18574199  0.4453001 ]
 [-1.24687346  0.22286625 -0.53528056]
 [-1.37386905 -0.13606376 -0.19630996]]
1.0
1.0
1.0
[[ 0.32  1.2  -1.56]
 [-0.29  1.25  0.59]
 [-0.25  0.87 -0.82]]
[[ 0.  1. -2.]
 [-1.  1.  0.]
 [-1.  0. -1.]]
[[ 1.  2. -1.]
 [-0.  2.  1.]
 [-0.  1. -0.]]


In [ ]:
print(np.sin(np.pi/6))
print(np.cos(np.pi/3))
print(np.tan(np.pi/4))
print(np.tanh(-10))

0.49999999999999994
0.5000000000000001
0.9999999999999999
-0.9999999958776927


In [ ]:
np.nan #not a number
#np.log(-1) => nan
print(np.isnan([1,2,np.nan,3,4]))
np.inf #infinite
print(np.isinf([1,2,3,4,np.inf]))

[False False  True False False]
[False False False False  True]


In [ ]:
A=np.random.randn(3,4)
print(A)
print(np.max(A))
print(np.max(A,axis=0)) #열로비교
print(np.max(A,axis=1)) #행으로비교 1행3열
print(np.max(A,axis=0,keepdims=True)) 
print(np.max(A,axis=1,keepdims=True))
print(np.min(A))
print(np.min(A,axis=0))
print(np.argmax(A))
print(np.argmax(A,axis=0)) #각 열에서 가장 큰 애가 존재하는 인덱스
print(np.argmax(A,axis=1)) #각 행에서 가장 큰 애가 존재하는 인덱스

[[ 0.36965421 -0.88576601  0.26261903  0.38801186]
 [ 0.74565176 -2.19279965  0.81669976 -0.68452144]
 [ 1.24846181 -0.15662415 -1.23968067  0.30046458]]
1.248461807807021
[ 1.24846181 -0.15662415  0.81669976  0.38801186]
[0.38801186 0.81669976 1.24846181]
[[ 1.24846181 -0.15662415  0.81669976  0.38801186]]
[[0.38801186]
 [0.81669976]
 [1.24846181]]
-2.192799653981449
[ 0.36965421 -2.19279965 -1.23968067 -0.68452144]
8
[2 2 1 0]
[3 2 0]


In [ ]:
a=np.random.randn(6,1)
print(a)
print()
a_sorted=np.sort(a,axis=0) #가로로 정렬하는 것이 default, 오름차순
print(a_sorted)
print()
print(np.flipud(a_sorted)) #내림차순

[[ 1.37532357]
 [ 0.23678743]
 [-0.40496711]
 [-0.70406968]
 [ 1.01976156]
 [ 0.8768926 ]]

[[-0.70406968]
 [-0.40496711]
 [ 0.23678743]
 [ 0.8768926 ]
 [ 1.01976156]
 [ 1.37532357]]

[[ 1.37532357]
 [ 1.01976156]
 [ 0.8768926 ]
 [ 0.23678743]
 [-0.40496711]
 [-0.70406968]]


In [ ]:
A=np.random.randn(3,4)
print(A)
print(np.sum(A)) 
print(np.sum(A,axis=1)) #1x3
print(np.sum(A,axis=1,keepdims=True)) #3x1 2D array
print(np.mean(A))
print(np.mean(A,axis=1))
print(np.mean(A,axis=1,keepdims=True)) #3x1
print(np.std(A)) #standard deviation 표준편차

[[-0.07092585 -0.66202765 -0.52650576 -0.2367669 ]
 [-0.63200645  0.91146199  1.9563068   1.64357266]
 [ 1.9705244   0.24917241  0.33803889  0.21854772]]
5.159392260758869
[-1.49622616  3.879335    2.77628342]
[[-1.49622616]
 [ 3.879335  ]
 [ 2.77628342]]
0.4299493550632391
[-0.37405654  0.96983375  0.69407085]
[[-0.37405654]
 [ 0.96983375]
 [ 0.69407085]]
0.9320251154622029


In [ ]:
A=np.random.randint(1,5,size=(12,)) #1부터 5미만, size 12x1
print(A)
print(A.shape)
B=A.reshape(2,2,3) #d,r,c 
print(B)
print(B.ndim) #3-d

[3 2 1 3 1 3 1 2 4 2 3 4]
(12,)
[[[3 2 1]
  [3 1 3]]

 [[1 2 4]
  [2 3 4]]]
3


In [ ]:
a=np.array([1,2,3])
b=np.array([2,2,1])
print(np.sum(a*b)) #inner product
print(a)

a=a.reshape(3,1) #make a coloum vector
b=b.reshape(3,1)
print(a.transpose()@b) #inner product
print(a.T@b)

A=np.random.randn(4,3,2)
print(A.shape)
print(A.transpose(0,1,2).shape) #d, r, c  0->0, 1->1, 2->2
print(A.T.shape)
print(A.transpose(2,1,0).shape) #d, r, c  0->2, 1->1, 2->0

9
[1 2 3]
[[9]]
[[9]]
(4, 3, 2)
(4, 3, 2)
(2, 3, 4)
(2, 3, 4)


In [ ]:
A=np.arange(20)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) #-1을 마지막에 쓰면 4개의 행이 될 수 있도록 열의 수를 알아서 맞춤
print(A.reshape(2,5,-1).shape)
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) #2차원 행 벡터를 만듬
print(A.reshape(-1,1).shape) #2차원 열 벡터를 만듬

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
(4, 5)
(2, 5, 2)
(2, 2, 5)
(1, 20)
(20, 1)


In [ ]:
x=np.random.randn(2,3,4,5,6)

print(x[1,2,:,:,:].shape)
print(x[1,2,...].shape) #x[1,2,:,:,:] == x[1,2,...]
print(x[:,:,:,:,3].shape)
print(x[...,3].shape)
print(x[1,:,:,3,:].shape)
print(x[1,...,3,:].shape)  
#...?아직 잘모르겠음 대충 고차원슬라이싱

(4, 5, 6)
(4, 5, 6)
(2, 3, 4, 5)
(2, 3, 4, 5)
(3, 4, 6)
(3, 4, 6)


In [ ]:
A=np.ones((2,2))
B=np.zeros((2,2))

C=np.hstack([A,B]) #horizontal방향으로 쌓임
D=np.vstack([A,B]) #vertical방향으로 쌓임
E=np.block([A,B]) #horizontal방향으로 쌓임
F=np.block([[A],[B]]) #vertical방향으로 쌓임
G=np.block([ [[A]] , [[B]] ]) #dimension으로 쌓임
print(C)
print(D)
print(E)
print(F)
print(G.shape)


[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
[[1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [0. 0.]
 [0. 0.]]
(2, 2, 2)


In [ ]:
A=np.random.randn(1,1,1,3,1,1,4,1) #essence는는 3,4에 있음
print(A)
print(A.shape)
print(A.squeeze().shape) #불필요한 1을 없앰
print(A.squeeze(axis=(0,2,4,5)).shape) #원하는 차원만 없앨 수 있음

[[[[[[[[ 0.81530145]
       [-2.33358682]
       [ 0.57880522]
       [ 0.99299009]]]]



    [[[[-0.89990747]
       [-0.18702281]
       [ 1.16277479]
       [ 0.53180208]]]]



    [[[[-0.64159703]
       [ 0.77846374]
       [-0.53555425]
       [ 0.17217436]]]]]]]]
(1, 1, 1, 3, 1, 1, 4, 1)
(3, 4)
(1, 3, 4, 1)


In [ ]:
A=np.random.randn(3,4)

A1=A[np.newaxis,:,:] #add dimension, np.newaxis is None == True
#A1=A[None,:,:]
print(A1.shape)
A2=A[...,np.newaxis]
print(A2.shape)
A3=A[:,np.newaxis,:]
print(A3.shape)
print()
A1=np.expand_dims(A,axis=0)
print(A1.shape)
A2=np.expand_dims(A,axis=2)
print(A2.shape)
A3=np.expand_dims(A,axis=1)
print(A3.shape)
print()
A1=A1.reshape(1,3,4)
print(A1.shape)
A2=A2.reshape(3,4,1)
print(A2.shape)
A3=A3.reshape(3,1,4)
print(A3.shape)

#차원을 맞춰야하는 torch나 pyplot에 쓰임

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)

(1, 3, 4)
(3, 4, 1)
(3, 1, 4)
